#!/usr/bin/env bash
# Pi-hole service module for InitOps-Server
# Network-wide ad blocking & DNS filtering

install_pihole() {
    if state_is_done "pihole"; then
        log_info "Pi-hole already installed, skipping"
        return 0
    fi

    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would install Pi-hole via Docker"
        state_mark_done "pihole"
        return 0
    fi

    log_info "Installing Pi-hole..."

    # Ensure Docker is installed
    if ! command -v docker &>/dev/null; then
        install_docker
    fi

    # Create Pi-hole directory
    mkdir -p /opt/pihole/etc-pihole /opt/pihole/etc-dnsmasq.d

    # Generate random password if not set
    local pihole_password
    pihole_password=$(state_get "pihole_password")
    if [[ -z "${pihole_password}" ]]; then
        pihole_password=$(openssl rand -base64 12)
        state_set "pihole_password" "${pihole_password}"
    fi

    # Pull Pi-hole image
    pull_docker_image "pihole/pihole:latest"

    # Run Pi-hole container
    docker run -d \
        --name pihole \
        --restart unless-stopped \
        -p 53:53/tcp -p 53:53/udp \
        -p 8080:80 \
        -p 443:443 \
        -e TZ="$(cat /etc/timezone 2>/dev/null || echo UTC)" \
        -e WEBPASSWORD="${pihole_password}" \
        -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 \
        -v /opt/pihole/etc-pihole:/etc/pihole \
        -v /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d \
        --cap-add=NET_ADMIN \
        pihole/pihole:latest

    # Wait for Pi-hole to be ready
    sleep 10
    wait_for_port "localhost" 8080 60

    log_success "Pi-hole installed"
    log_info "Admin UI: http://$(get_primary_ip):8080/admin"
    log_info "Password: ${pihole_password}"
    log_warn "Save this password! It won't be shown again."

    state_mark_done "pihole"
}

configure_pihole_dns() {
    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would configure system DNS to use Pi-hole"
        return 0
    fi

    log_info "Configuring system to use Pi-hole as DNS..."

    # Update resolv.conf to use local Pi-hole
    cat > /etc/resolv.conf << EOF
# Generated by InitOps-Server
nameserver 127.0.0.1
options edns0 trust-ad
search .
EOF

    # Make it immutable to prevent overwrites
    chattr +i /etc/resolv.conf 2>/dev/null || true
}