#!/usr/bin/env bash
# Nginx module for InitOps-Server
# Reverse proxy with SSL and authentication

setup_nginx() {
    if state_is_done "nginx"; then
        log_info "Nginx already configured, skipping"
        return 0
    fi

    if [[ "${DRY_RUN}" == "true" ]]; then
        log_info "[DRY RUN] Would configure nginx reverse proxy"
        state_mark_done "nginx"
        return 0
    fi

    log_info "Installing and configuring nginx..."

    # Install nginx
    apt update
    DEBIAN_FRONTEND=noninteractive apt install -y nginx apache2-utils

    # Generate SSL certificates
    setup_ssl

    # Generate nginx configuration
    generate_nginx_config

    # Enable and start nginx
    systemctl enable --now nginx

    # Configure firewall
    ufw allow 'Nginx Full'

    log_success "Nginx reverse proxy configured"
    state_mark_done "nginx"
}

setup_ssl() {
    local domain="${CONFIG[nginx_domain]}"
    local ssl_type="${CONFIG[nginx_ssl]}"
    local cert_dir="/etc/nginx/ssl"

    mkdir -p "${cert_dir}"

    case "${ssl_type}" in
        letsencrypt)
            if [[ "${domain}" == "local" ]]; then
                log_warn "Let's Encrypt requires a valid domain, falling back to self-signed"
                generate_self_signed_cert "${cert_dir}"
            else
                install_letsencrypt "${domain}" "${cert_dir}"
            fi
            ;;
        self-signed|*)
            generate_self_signed_cert "${cert_dir}"
            ;;
    esac
}

generate_self_signed_cert() {
    local cert_dir="$1"
    local cert_file="${cert_dir}/server.crt"
    local key_file="${cert_dir}/server.key"

    if [[ -f "${cert_file}" && -f "${key_file}" ]]; then
        log_info "Self-signed certificate already exists"
        return 0
    fi

    log_info "Generating self-signed SSL certificate..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "${key_file}" \
        -out "${cert_file}" \
        -subj "/C=US/ST=State/L=City/O=InitOps/OU=Server/CN=$(hostname)" \
        -addext "subjectAltName=DNS:$(hostname),IP:$(get_primary_ip)"

    chmod 600 "${key_file}"
    chmod 644 "${cert_file}"
}

install_letsencrypt() {
    local domain="$1"
    local cert_dir="$2"

    log_info "Installing Certbot for Let's Encrypt..."
    apt update
    DEBIAN_FRONTEND=noninteractive apt install -y certbot python3-certbot-nginx

    log_info "Obtaining Let's Encrypt certificate for ${domain}..."
    certbot --nginx -d "${domain}" --non-interactive --agree-tos --email "admin@${domain}" --redirect

    # Copy certs to nginx ssl directory
    cp "/etc/letsencrypt/live/${domain}/fullchain.pem" "${cert_dir}/server.crt"
    cp "/etc/letsencrypt/live/${domain}/privkey.pem" "${cert_dir}/server.key"

    # Setup auto-renewal
    systemctl enable --now certbot.timer
}

generate_nginx_config() {
    local domain="${CONFIG[nginx_domain]}"
    local ssl_type="${CONFIG[nginx_ssl]}"
    local auth_provider="${CONFIG[nginx_auth_provider]}"
    local config_file="/etc/nginx/sites-available/initops"

    log_info "Generating nginx configuration..."

    cat > "${config_file}" << EOF
# InitOps-Server nginx configuration
# Generated by initops.sh

# Upstream services
upstream cockpit_backend {
    server localhost:9090;
}

upstream grafana_backend {
    server localhost:3000;
}

upstream n8n_backend {
    server localhost:5678;
}

upstream pihole_backend {
    server localhost:8080;
}

upstream ollama_backend {
    server localhost:11434;
}

upstream sterling_pdf_backend {
    server localhost:3001;
}

# Rate limiting
limit_req_zone \$binary_remote_addr zone=api:10m rate=10r/s;
limit_req_zone \$binary_remote_addr zone=login:10m rate=1r/s;

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${domain} _;

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect all other traffic to HTTPS
    location / {
        return 301 https://\$host\$request_uri;
    }
}

# Main HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${domain} _;

    # SSL Configuration
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Authentication
EOF

    # Add authentication based on provider
    case "${auth_provider}" in
        basic)
            cat >> "${config_file}" << 'EOF'
    auth_basic "InitOps-Server";
    auth_basic_user_file /etc/nginx/.htpasswd;
EOF
            ;;
        authelia)
            cat >> "${config_file}" << 'EOF'
    # Authelia forward auth
    auth_request /authelia/verify;
    auth_request_set \$user \$upstream_http_remote_user;
    auth_request_set \$groups \$upstream_http_remote_groups;

    location /authelia/ {
        internal;
        proxy_pass http://localhost:9091;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URL \$scheme://\$host\$request_uri;
    }
EOF
            ;;
        oidc)
            cat >> "${config_file}" << 'EOF'
    # OIDC authentication (requires nginx-plus or openresty with lua)
    # Placeholder for OIDC configuration
    # auth_request /oidc/verify;
EOF
            ;;
    esac

    cat >> "${config_file}" << 'EOF'

    # Dashboard - Main landing page
    location / {
        proxy_pass http://localhost:8081;  # Custom dashboard (to be implemented)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Cockpit - System administration
    location /cockpit/ {
        proxy_pass https://cockpit_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 900s;
    }

    # Grafana - Metrics and dashboards
    location /grafana/ {
        proxy_pass http://grafana_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # n8n - Workflow automation
    location /n8n/ {
        proxy_pass http://n8n_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }

    # Pi-hole - DNS management
    location /pihole/ {
        proxy_pass http://pihole_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Ollama - LLM API
    location /ollama/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://ollama_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # Sterling PDF - PDF toolkit
    location /pdf/ {
        proxy_pass http://sterling_pdf_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        client_max_body_size 100M;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
EOF

    # Enable site
    ln -sf "${config_file}" /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default

    # Test configuration
    nginx -t

    # Create htpasswd for basic auth
    if [[ "${auth_provider}" == "basic" ]]; then
        setup_basic_auth
    fi
}

setup_basic_auth() {
    local htpasswd_file="/etc/nginx/.htpasswd"
    local users="${CONFIG[nginx_auth_users]:-}"

    if [[ ! -f "${htpasswd_file}" ]]; then
        touch "${htpasswd_file}"
    fi

    # Add default admin user if none exist
    if [[ ! -s "${htpasswd_file}" ]]; then
        log_info "Creating default admin user (password: changeme)"
        echo "admin:$(openssl passwd -apr1 'changeme')" > "${htpasswd_file}"
        log_warn "Default admin password is 'changeme' - CHANGE THIS IMMEDIATELY"
    fi
}